/*
AUTOGENERATED - DON'T EDIT
Your edits in this file will be overwritten in the next build!
Modify the docusaurus.config.js file at your site's root instead.
*/
export default {
  "title": "Save Guide",
  "tagline": "Magical Internet Organization Grimoire",
  "url": "https://github.com",
  "baseUrl": "/guide/",
  "favicon": "img/rg-icon.png",
  "onBrokenLinks": "ignore",
  "organizationName": "Save-Dao",
  "projectName": "Mio-grimoire",
  "themeConfig": {
    "navbar": {
      "logo": {
        "alt": "Save Dao Logo",
        "src": "img/rg-icon.png"
      },
      "items": [
        {
          "href": "https://www.adbongo.io",
          "label": "Main Site",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "copyright": "Copyright © 2022 SAVE, DAO",
      "links": []
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage"
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": []
    },
    "hideableSidebar": false,
    "autoCollapseSidebarCategories": false,
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "/Users/baba/Documents/GitHub/guide/sidebars.js",
          "editUrl": "https://github.com/raid-guild/handbook/edit/master/"
        },
        "theme": {
          "customCss": "/Users/baba/Documents/GitHub/guide/src/css/custom.css"
        }
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onBrokenMarkdownLinks": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "titleDelimiter": "|",
  "noIndex": false
};